#!/bin/sh

base_dir="~/RECYCLE"

scr=$1

dest="base_dir/scr"

dest_dir=(dirname "dest")

if ! [ -e "$1" ] ; 
  then
echo "File '$1' not found"
fi 

gzip "$1"
mkdir -p "dest_dir/"
mv "$1.gz" "dest_dir/"
find "base_dir/" -atime +7 -delete 
